### PR TITLE
Bug fix: Fixed Partner select not showing all partners

### LINKED ISSUE #160: Bug: Add partner drop-down not listing all partners
• Adding opportunities
        ◦ When trying to add a vol opp you go to that page and the dropdown of partner_name only has the first "page" of partner-agencies to choose from.  You can't pick from any partner-agency – it needs to show all of them in that dropdown, not just a select few.

### PR DESCRIPTION
**Pull request by Alex-Cannon**
Close #160 

1. Added SelectOneSearch component to replace the previous Select component for the partner_name field in POST/PUT opportunities. This allows users to _search_ and _select_ a partner, rather than selected a partner by itself. I felt this was necessary considering that VOA has a ton of data.

Test this:
Use the POST/PUT opportunity forms with the new functionality.

I tested this with POSTing an opportunity.

### CODE REVIEW

**Comment by stevenabadie** [comment]
@Alex-Cannon I tested this one but am not seeing any results when searching for a partner in the Add Opportunities form. I've search known partners but still see 'No Results'

**Comment by Alex-Cannon** [comment]
@stevenabadie do you have partners in your database? As of my knowledge, whoosh is setup to match whole words, not partial matches.

When I search "volunteers", I see "volunteers of america".
When I search "vol", I see 0 results.

This should be expected.

**Comment by Alex-Cannon** [comment]
@stevenabadie I tested this again. It works for me. The search must match an exact word in the partner_name. Then, you must choose the partner from the drop-down instead of typing it in.

Let me know if it still doesn't work for you.

**Comment by stevenabadie** [comment]
This is merged in

**Pull request closed without merging**
